---
title: "Description of Data Sources"
output:
  html_document: default
---


\
\


A large portion of the data used for this project will be obtained from [NYC Open Data](https://data.cityofnewyork.us/), a project intended to make New York City data available for public use. Here's the site's own description:

*"NYC Open Data makes the wealth of public data generated by various New York City agencies and other City organizations available for public use. As part of an initiative to improve the accessibility, transparency, and accountability of City government, this catalog offers access to a repository of government-produced, machine-readable data sets."*

\


#### Data used in the current app prototype: 

* Coordinates of polygons defining each school zone: [2016-2017 School Zones](https://data.cityofnewyork.us/Education/2016-2017-School-Zones/ux7j-iww6) 

* School quality: [School Progress Report 2010-2011](https://data.cityofnewyork.us/Education/School-Progress-Report-2010-2011/upwt-zvh3)^1^

* Subway stations and their subway lines: [Subway Stations](https://data.cityofnewyork.us/Transportation/Subway-Stations/arq3-7z49)

\


#### Tentative data to add to future versions of the app: 

* Summary of neighborhood sales^2^, for defining an "Affordability" preference: [Manhattan](https://data.cityofnewyork.us/Housing-Development/DOF-Summary-of-Neighborhood-Sales-for-Manhattan-fo/5yay-3jd5), 
[Brooklyn](https://data.cityofnewyork.us/Housing-Development/DOF-Summary-of-Neighborhood-Sales-for-Brooklyn-for/nbun-a9vi), 
[Queens](https://data.cityofnewyork.us/Housing-Development/DOF-Summary-of-Neighborhood-Sales-for-Queens-for-C/948r-3ads),
[Bronx](https://data.cityofnewyork.us/Housing-Development/DOF-Summary-of-Neighborhood-Sales-for-the-Bronx-fo/w4v6-3sdt), 
[Staten Island](https://data.cityofnewyork.us/Housing-Development/DOF-Summary-of-Neighborhood-Sales-for-Staten-Islan/ntbr-wib6)


* Coordinates of all city lots zoned for commercial use, for defining a "Proximity to businesses" preference^3^: [Primary Commercial Zoning by Lot](https://data.cityofnewyork.us/Business/Primary-Commercial-Zoning-by-lot/pwhj-ikym)

* Geographical information about felony incidents, for defining a "Safety" preference:
[NYPD Major Felony Incident Map](https://data.cityofnewyork.us/Public-Safety/NYPD-7-Major-Felony-Incident-Map/dvh8-u7es)

* Coordinates of perimeters of all NYC parks, for defining a "Park proximity" preference: [Parks Properties](https://data.cityofnewyork.us/City-Government/Parks-Properties/rjaj-zgq7)

* Coordinates of all trees in NYC streets, for defining a "Greenery" preference: [2015 Street Tree Census Tree Data](https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh)


\


<small>
Notes:

1. This data is relatively old. I intend to find more recent data on "quality" of public schools.
2. This data is relatively old (2009). I intend to find more recent sales data, possibly from another source.
3. Ideally, the app will allow the user to define separate preferences for proximity to restaurants/bars and shopping. So far, I have only found data on commercial space, which lumps together these two (and other) types of businesses.



